name: docs
on:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      - name: Deploy to main site doc/multiwfn
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: wxyhgk/wxyhgk.github.io
          publish_branch: main
          publish_dir: ./site
          destination_dir: doc/multiwfn
          keep_files: true
